language: csharp
solution: PrestaSharp.sln

services:
  - docker

script:
  - msbuild /p:Configuration=Debug PrestaSharp.sln

before_install:
  - sudo apt-get install nunit-console
  # create a network for containers to communicate
  - docker network create prestashop-net
  # launch mysql 5.7 container
  - docker run -ti --name some-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
  # launch prestashop container
  - docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -p 8080:80 -d prestashop/prestashop

before_script:
  - nuget restore PrestaSharp.sln
after_script:
  - nunit-console PrestaSharp.IntegrationTests/bin/Debug/netcoreapp2.1/PrestaSharp.IntegrationTests.dll