//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_access
    {
        public long id_profile { get; set; }
        public long id_tab { get; set; }
        public int view { get; set; }
        public int add { get; set; }
        public int edit { get; set; }
        public int delete { get; set; }
    }
}
