//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_attribute_impact
    {
        public long id_attribute_impact { get; set; }
        public long id_product { get; set; }
        public long id_attribute { get; set; }
        public decimal weight { get; set; }
        public decimal price { get; set; }
    }
}
