//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_badge
    {
        public int id_badge { get; set; }
        public int id_ps_badge { get; set; }
        public string type { get; set; }
        public int id_group { get; set; }
        public int group_position { get; set; }
        public int scoring { get; set; }
        public bool validated { get; set; }
    }
}
