//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_country
    {
        public long id_country { get; set; }
        public long id_zone { get; set; }
        public long id_currency { get; set; }
        public string iso_code { get; set; }
        public int call_prefix { get; set; }
        public bool active { get; set; }
        public bool contains_states { get; set; }
        public bool need_identification_number { get; set; }
        public bool need_zip_code { get; set; }
        public string zip_code_format { get; set; }
        public bool display_tax_label { get; set; }
    }
}
