//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_condition
    {
        public int id_condition { get; set; }
        public int id_ps_condition { get; set; }
        public string type { get; set; }
        public string request { get; set; }
        public string @operator { get; set; }
        public string value { get; set; }
        public string result { get; set; }
        public string calculation_type { get; set; }
        public string calculation_detail { get; set; }
        public bool validated { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
