//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_cart
    {
        public long id_cart { get; set; }
        public long id_shop_group { get; set; }
        public long id_shop { get; set; }
        public long id_carrier { get; set; }
        public string delivery_option { get; set; }
        public long id_lang { get; set; }
        public long id_address_delivery { get; set; }
        public long id_address_invoice { get; set; }
        public long id_currency { get; set; }
        public long id_customer { get; set; }
        public long id_guest { get; set; }
        public string secure_key { get; set; }
        public bool recyclable { get; set; }
        public bool gift { get; set; }
        public string gift_message { get; set; }
        public bool mobile_theme { get; set; }
        public bool allow_seperated_package { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
