//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_currency
    {
        public long id_currency { get; set; }
        public string name { get; set; }
        public string iso_code { get; set; }
        public string iso_code_num { get; set; }
        public string sign { get; set; }
        public bool blank { get; set; }
        public bool format { get; set; }
        public bool decimals { get; set; }
        public decimal conversion_rate { get; set; }
        public bool deleted { get; set; }
        public bool active { get; set; }
    }
}
