//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_category
    {
        public long id_category { get; set; }
        public long id_parent { get; set; }
        public long id_shop_default { get; set; }
        public byte level_depth { get; set; }
        public long nleft { get; set; }
        public long nright { get; set; }
        public bool active { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
        public long position { get; set; }
        public bool is_root_category { get; set; }
    }
}
