//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_carrier
    {
        public long id_carrier { get; set; }
        public long id_reference { get; set; }
        public Nullable<long> id_tax_rules_group { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public bool active { get; set; }
        public bool deleted { get; set; }
        public bool shipping_handling { get; set; }
        public bool range_behavior { get; set; }
        public bool is_module { get; set; }
        public bool is_free { get; set; }
        public bool shipping_external { get; set; }
        public bool need_range { get; set; }
        public string external_module_name { get; set; }
        public int shipping_method { get; set; }
        public long position { get; set; }
        public Nullable<int> max_width { get; set; }
        public Nullable<int> max_height { get; set; }
        public Nullable<int> max_depth { get; set; }
        public Nullable<decimal> max_weight { get; set; }
        public Nullable<int> grade { get; set; }
    }
}
