//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_customization
    {
        public long id_customization { get; set; }
        public long id_product_attribute { get; set; }
        public long id_address_delivery { get; set; }
        public long id_cart { get; set; }
        public int id_product { get; set; }
        public int quantity { get; set; }
        public int quantity_refunded { get; set; }
        public int quantity_returned { get; set; }
        public bool in_cart { get; set; }
    }
}
