//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_cart_product
    {
        public long id_cart { get; set; }
        public long id_product { get; set; }
        public Nullable<long> id_address_delivery { get; set; }
        public long id_shop { get; set; }
        public Nullable<long> id_product_attribute { get; set; }
        public long quantity { get; set; }
        public System.DateTime date_add { get; set; }
    }
}
