//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_configuration
    {
        public long id_configuration { get; set; }
        public Nullable<long> id_shop_group { get; set; }
        public Nullable<long> id_shop { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
