//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_customer_thread
    {
        public long id_customer_thread { get; set; }
        public long id_shop { get; set; }
        public long id_lang { get; set; }
        public long id_contact { get; set; }
        public Nullable<long> id_customer { get; set; }
        public Nullable<long> id_order { get; set; }
        public Nullable<long> id_product { get; set; }
        public string status { get; set; }
        public string email { get; set; }
        public string token { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
