//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_connections_page
    {
        public long id_connections { get; set; }
        public long id_page { get; set; }
        public System.DateTime time_start { get; set; }
        public Nullable<System.DateTime> time_end { get; set; }
    }
}
