//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_delivery
    {
        public long id_delivery { get; set; }
        public Nullable<long> id_shop { get; set; }
        public Nullable<long> id_shop_group { get; set; }
        public long id_carrier { get; set; }
        public Nullable<long> id_range_price { get; set; }
        public Nullable<long> id_range_weight { get; set; }
        public long id_zone { get; set; }
        public decimal price { get; set; }
    }
}
