//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_guest
    {
        public long id_guest { get; set; }
        public Nullable<long> id_operating_system { get; set; }
        public Nullable<long> id_web_browser { get; set; }
        public Nullable<long> id_customer { get; set; }
        public Nullable<bool> javascript { get; set; }
        public Nullable<int> screen_resolution_x { get; set; }
        public Nullable<int> screen_resolution_y { get; set; }
        public Nullable<byte> screen_color { get; set; }
        public Nullable<bool> sun_java { get; set; }
        public Nullable<bool> adobe_flash { get; set; }
        public Nullable<bool> adobe_director { get; set; }
        public Nullable<bool> apple_quicktime { get; set; }
        public Nullable<bool> real_player { get; set; }
        public Nullable<bool> windows_media { get; set; }
        public string accept_language { get; set; }
        public bool mobile_theme { get; set; }
    }
}
