//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_image_type
    {
        public long id_image_type { get; set; }
        public string name { get; set; }
        public long width { get; set; }
        public long height { get; set; }
        public bool products { get; set; }
        public bool categories { get; set; }
        public bool manufacturers { get; set; }
        public bool suppliers { get; set; }
        public bool scenes { get; set; }
        public bool stores { get; set; }
    }
}
