//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_lang
    {
        public long id_lang { get; set; }
        public string name { get; set; }
        public byte active { get; set; }
        public string iso_code { get; set; }
        public string language_code { get; set; }
        public string date_format_lite { get; set; }
        public string date_format_full { get; set; }
        public bool is_rtl { get; set; }
    }
}
