//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_log
    {
        public long id_log { get; set; }
        public bool severity { get; set; }
        public Nullable<int> error_code { get; set; }
        public string message { get; set; }
        public string object_type { get; set; }
        public Nullable<long> object_id { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
