//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_newsletter
    {
        public int id { get; set; }
        public long id_shop { get; set; }
        public long id_shop_group { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> newsletter_date_add { get; set; }
        public string ip_registration_newsletter { get; set; }
        public string http_referer { get; set; }
        public bool active { get; set; }
    }
}
