//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_order_slip
    {
        public long id_order_slip { get; set; }
        public decimal conversion_rate { get; set; }
        public long id_customer { get; set; }
        public long id_order { get; set; }
        public byte shipping_cost { get; set; }
        public decimal amount { get; set; }
        public decimal shipping_cost_amount { get; set; }
        public bool partial { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
