//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_order_cart_rule
    {
        public long id_order_cart_rule { get; set; }
        public long id_order { get; set; }
        public long id_cart_rule { get; set; }
        public Nullable<long> id_order_invoice { get; set; }
        public string name { get; set; }
        public decimal value { get; set; }
        public decimal value_tax_excl { get; set; }
        public bool free_shipping { get; set; }
    }
}
