//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_order_payment
    {
        public int id_order_payment { get; set; }
        public string order_reference { get; set; }
        public long id_currency { get; set; }
        public decimal amount { get; set; }
        public string payment_method { get; set; }
        public decimal conversion_rate { get; set; }
        public string transaction_id { get; set; }
        public string card_number { get; set; }
        public string card_brand { get; set; }
        public string card_expiration { get; set; }
        public string card_holder { get; set; }
        public System.DateTime date_add { get; set; }
    }
}
