//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_order_carrier
    {
        public int id_order_carrier { get; set; }
        public long id_order { get; set; }
        public long id_carrier { get; set; }
        public Nullable<long> id_order_invoice { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> shipping_cost_tax_excl { get; set; }
        public Nullable<decimal> shipping_cost_tax_incl { get; set; }
        public string tracking_number { get; set; }
        public System.DateTime date_add { get; set; }
    }
}
