//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_orders
    {
        public long id_order { get; set; }
        public string reference { get; set; }
        public long id_shop_group { get; set; }
        public long id_shop { get; set; }
        public long id_carrier { get; set; }
        public long id_lang { get; set; }
        public long id_customer { get; set; }
        public long id_cart { get; set; }
        public long id_currency { get; set; }
        public long id_address_delivery { get; set; }
        public long id_address_invoice { get; set; }
        public long current_state { get; set; }
        public string secure_key { get; set; }
        public string payment { get; set; }
        public decimal conversion_rate { get; set; }
        public string module { get; set; }
        public bool recyclable { get; set; }
        public bool gift { get; set; }
        public string gift_message { get; set; }
        public bool mobile_theme { get; set; }
        public string shipping_number { get; set; }
        public decimal total_discounts { get; set; }
        public decimal total_discounts_tax_incl { get; set; }
        public decimal total_discounts_tax_excl { get; set; }
        public decimal total_paid { get; set; }
        public decimal total_paid_tax_incl { get; set; }
        public decimal total_paid_tax_excl { get; set; }
        public decimal total_paid_real { get; set; }
        public decimal total_products { get; set; }
        public decimal total_products_wt { get; set; }
        public decimal total_shipping { get; set; }
        public decimal total_shipping_tax_incl { get; set; }
        public decimal total_shipping_tax_excl { get; set; }
        public decimal carrier_tax_rate { get; set; }
        public decimal total_wrapping { get; set; }
        public decimal total_wrapping_tax_incl { get; set; }
        public decimal total_wrapping_tax_excl { get; set; }
        public long invoice_number { get; set; }
        public long delivery_number { get; set; }
        public System.DateTime invoice_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public long valid { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
