//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_order_return
    {
        public long id_order_return { get; set; }
        public long id_customer { get; set; }
        public long id_order { get; set; }
        public bool state { get; set; }
        public string question { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
