//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_order_invoice
    {
        public long id_order_invoice { get; set; }
        public int id_order { get; set; }
        public int number { get; set; }
        public int delivery_number { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public decimal total_discount_tax_excl { get; set; }
        public decimal total_discount_tax_incl { get; set; }
        public decimal total_paid_tax_excl { get; set; }
        public decimal total_paid_tax_incl { get; set; }
        public decimal total_products { get; set; }
        public decimal total_products_wt { get; set; }
        public decimal total_shipping_tax_excl { get; set; }
        public decimal total_shipping_tax_incl { get; set; }
        public long shipping_tax_computation_method { get; set; }
        public decimal total_wrapping_tax_excl { get; set; }
        public decimal total_wrapping_tax_incl { get; set; }
        public string note { get; set; }
        public System.DateTime date_add { get; set; }
    }
}
