//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_product_lang
    {
        public long id_product { get; set; }
        public long id_shop { get; set; }
        public long id_lang { get; set; }
        public string description { get; set; }
        public string description_short { get; set; }
        public string link_rewrite { get; set; }
        public string meta_description { get; set; }
        public string meta_keywords { get; set; }
        public string meta_title { get; set; }
        public string name { get; set; }
        public string available_now { get; set; }
        public string available_later { get; set; }
    }
}
