//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_page_viewed
    {
        public long id_page { get; set; }
        public long id_shop_group { get; set; }
        public long id_shop { get; set; }
        public long id_date_range { get; set; }
        public long counter { get; set; }
    }
}
