//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_product_shop
    {
        public long id_product { get; set; }
        public long id_shop { get; set; }
        public Nullable<long> id_category_default { get; set; }
        public long id_tax_rules_group { get; set; }
        public bool on_sale { get; set; }
        public bool online_only { get; set; }
        public decimal ecotax { get; set; }
        public long minimal_quantity { get; set; }
        public decimal price { get; set; }
        public decimal wholesale_price { get; set; }
        public string unity { get; set; }
        public decimal unit_price_ratio { get; set; }
        public decimal additional_shipping_cost { get; set; }
        public sbyte customizable { get; set; }
        public sbyte uploadable_files { get; set; }
        public sbyte text_fields { get; set; }
        public bool active { get; set; }
        public string redirect_type { get; set; }
        public long id_product_redirected { get; set; }
        public bool available_for_order { get; set; }
        public System.DateTime available_date { get; set; }
        public string condition { get; set; }
        public bool show_price { get; set; }
        public bool indexed { get; set; }
        public string visibility { get; set; }
        public Nullable<long> cache_default_attribute { get; set; }
        public bool advanced_stock_management { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
    }
}
