//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_pagenotfound
    {
        public long id_pagenotfound { get; set; }
        public long id_shop { get; set; }
        public long id_shop_group { get; set; }
        public string request_uri { get; set; }
        public string http_referer { get; set; }
        public System.DateTime date_add { get; set; }
    }
}
