//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_product_download
    {
        public long id_product_download { get; set; }
        public long id_product { get; set; }
        public string display_filename { get; set; }
        public string filename { get; set; }
        public System.DateTime date_add { get; set; }
        public Nullable<System.DateTime> date_expiration { get; set; }
        public Nullable<long> nb_days_accessible { get; set; }
        public Nullable<long> nb_downloadable { get; set; }
        public bool active { get; set; }
        public bool is_shareable { get; set; }
    }
}
