//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_product_attribute_shop
    {
        public long id_product_attribute { get; set; }
        public long id_shop { get; set; }
        public decimal wholesale_price { get; set; }
        public decimal price { get; set; }
        public decimal ecotax { get; set; }
        public decimal weight { get; set; }
        public decimal unit_price_impact { get; set; }
        public bool default_on { get; set; }
        public long minimal_quantity { get; set; }
        public System.DateTime available_date { get; set; }
    }
}
