//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_referrer_shop
    {
        public long id_referrer { get; set; }
        public long id_shop { get; set; }
        public Nullable<int> cache_visitors { get; set; }
        public Nullable<int> cache_visits { get; set; }
        public Nullable<int> cache_pages { get; set; }
        public Nullable<int> cache_registrations { get; set; }
        public Nullable<int> cache_orders { get; set; }
        public Nullable<decimal> cache_sales { get; set; }
        public Nullable<decimal> cache_reg_rate { get; set; }
        public Nullable<decimal> cache_order_rate { get; set; }
    }
}
