//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_referrer
    {
        public long id_referrer { get; set; }
        public string name { get; set; }
        public string passwd { get; set; }
        public string http_referer_regexp { get; set; }
        public string http_referer_like { get; set; }
        public string request_uri_regexp { get; set; }
        public string request_uri_like { get; set; }
        public string http_referer_regexp_not { get; set; }
        public string http_referer_like_not { get; set; }
        public string request_uri_regexp_not { get; set; }
        public string request_uri_like_not { get; set; }
        public decimal base_fee { get; set; }
        public decimal percent_fee { get; set; }
        public decimal click_fee { get; set; }
        public System.DateTime date_add { get; set; }
    }
}
