//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_supply_order_state
    {
        public long id_supply_order_state { get; set; }
        public bool delivery_note { get; set; }
        public bool editable { get; set; }
        public bool receipt_state { get; set; }
        public bool pending_receipt { get; set; }
        public bool enclosed { get; set; }
        public string color { get; set; }
    }
}
