//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_stock_mvt
    {
        public decimal id_stock_mvt { get; set; }
        public long id_stock { get; set; }
        public Nullable<long> id_order { get; set; }
        public Nullable<long> id_supply_order { get; set; }
        public long id_stock_mvt_reason { get; set; }
        public long id_employee { get; set; }
        public string employee_lastname { get; set; }
        public string employee_firstname { get; set; }
        public long physical_quantity { get; set; }
        public System.DateTime date_add { get; set; }
        public bool sign { get; set; }
        public Nullable<decimal> price_te { get; set; }
        public Nullable<decimal> last_wa { get; set; }
        public Nullable<decimal> current_wa { get; set; }
        public Nullable<decimal> referer { get; set; }
    }
}
