//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_scene_products
    {
        public long id_scene { get; set; }
        public long id_product { get; set; }
        public int x_axis { get; set; }
        public int y_axis { get; set; }
        public int zone_width { get; set; }
        public int zone_height { get; set; }
    }
}
