//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_shop_url
    {
        public long id_shop_url { get; set; }
        public long id_shop { get; set; }
        public string domain { get; set; }
        public string domain_ssl { get; set; }
        public string physical_uri { get; set; }
        public string virtual_uri { get; set; }
        public bool main { get; set; }
        public bool active { get; set; }
    }
}
