//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_stock
    {
        public long id_stock { get; set; }
        public long id_warehouse { get; set; }
        public long id_product { get; set; }
        public long id_product_attribute { get; set; }
        public string reference { get; set; }
        public string ean13 { get; set; }
        public string upc { get; set; }
        public long physical_quantity { get; set; }
        public long usable_quantity { get; set; }
        public Nullable<decimal> price_te { get; set; }
    }
}
