//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_supply_order
    {
        public long id_supply_order { get; set; }
        public long id_supplier { get; set; }
        public string supplier_name { get; set; }
        public long id_lang { get; set; }
        public long id_warehouse { get; set; }
        public long id_supply_order_state { get; set; }
        public long id_currency { get; set; }
        public long id_ref_currency { get; set; }
        public string reference { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_upd { get; set; }
        public Nullable<System.DateTime> date_delivery_expected { get; set; }
        public Nullable<decimal> total_te { get; set; }
        public Nullable<decimal> total_with_discount_te { get; set; }
        public Nullable<decimal> total_tax { get; set; }
        public Nullable<decimal> total_ti { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<decimal> discount_value_te { get; set; }
        public Nullable<bool> is_template { get; set; }
    }
}
