//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_supply_order_history
    {
        public long id_supply_order_history { get; set; }
        public long id_supply_order { get; set; }
        public long id_employee { get; set; }
        public string employee_lastname { get; set; }
        public string employee_firstname { get; set; }
        public long id_state { get; set; }
        public System.DateTime date_add { get; set; }
    }
}
