//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_shop_group
    {
        public long id_shop_group { get; set; }
        public string name { get; set; }
        public bool share_customer { get; set; }
        public bool share_order { get; set; }
        public bool share_stock { get; set; }
        public bool active { get; set; }
        public bool deleted { get; set; }
    }
}
