//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_specific_price_rule
    {
        public long id_specific_price_rule { get; set; }
        public string name { get; set; }
        public long id_shop { get; set; }
        public long id_currency { get; set; }
        public long id_country { get; set; }
        public long id_group { get; set; }
        public int from_quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public decimal reduction { get; set; }
        public string reduction_type { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime to { get; set; }
    }
}
