//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_state
    {
        public long id_state { get; set; }
        public long id_country { get; set; }
        public long id_zone { get; set; }
        public string name { get; set; }
        public string iso_code { get; set; }
        public short tax_behavior { get; set; }
        public bool active { get; set; }
    }
}
