//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_supply_order_detail
    {
        public long id_supply_order_detail { get; set; }
        public long id_supply_order { get; set; }
        public long id_currency { get; set; }
        public long id_product { get; set; }
        public long id_product_attribute { get; set; }
        public string reference { get; set; }
        public string supplier_reference { get; set; }
        public string name { get; set; }
        public string ean13 { get; set; }
        public string upc { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public Nullable<decimal> unit_price_te { get; set; }
        public long quantity_expected { get; set; }
        public long quantity_received { get; set; }
        public Nullable<decimal> price_te { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<decimal> discount_value_te { get; set; }
        public Nullable<decimal> price_with_discount_te { get; set; }
        public Nullable<decimal> tax_rate { get; set; }
        public Nullable<decimal> tax_value { get; set; }
        public Nullable<decimal> price_ti { get; set; }
        public Nullable<decimal> tax_value_with_order_discount { get; set; }
        public Nullable<decimal> price_with_order_discount_te { get; set; }
    }
}
