//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_webservice_account
    {
        public int id_webservice_account { get; set; }
        public string key { get; set; }
        public string description { get; set; }
        public string class_name { get; set; }
        public sbyte is_module { get; set; }
        public string module_name { get; set; }
        public sbyte active { get; set; }
    }
}
