//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestaSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_warehouse_product_location
    {
        public long id_warehouse_product_location { get; set; }
        public long id_product { get; set; }
        public long id_product_attribute { get; set; }
        public long id_warehouse { get; set; }
        public string location { get; set; }
    }
}
